---
title: "Example Lakes"
output: 
  github_document: default
  html_document: default
date: "Last compiled on `r Sys.time()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(glmtools)
library(tidyverse)
base_dir <- here::here()
switch(Sys.info()[['sysname']],
       Windows= {warning("Windows testing not avaialable yet")},
       Linux  = {glm_exec <- file.path(base_dir, "binaries/ubuntu/20.04/glm_lastest/glm")},
       Darwin = {warning("Mac testing not avaialable yet")})
glm_exec <- file.path(base_dir, "binaries/ubuntu/20.04/glm")
run_sim <- function(lake, do_run, base_dir, glm_exec){
  if(do_run){
    setwd(file.path(base_dir, "glm-examples", lake))
    system2(glm_exec)
    setwd(base_dir)
  }
}
# If you want to run the simulations within the document, set `do_run = TRUE`.
do_run <- FALSE
```

# Falling Creek Reservoir (FCR)

```{r echo = FALSE}
lake <- "FCR"
lake_csv <- file.path(base_dir, "glm-examples", lake, "output/lake.csv") 
nc_file <- file.path(base_dir, "glm-examples", lake, "output/output.nc")
run_sim(lake, do_run, base_dir, glm_exec)
```

## Temperature profiles

```{r FCR, echo = FALSE}
plot_temp(nc_file, col_lim = c(0,30))
```

# Woods Lake

```{r echo = FALSE}
lake <- "Woods"
lake_csv <- file.path(base_dir, "glm-examples", lake, "output/lake.csv") 
nc_file <- file.path(base_dir, "glm-examples", lake, "output/output.nc")
run_sim(lake, do_run, base_dir, glm_exec)
```

## Temperature profiles

```{r Woods, echo = FALSE}
plot_temp(nc_file, col_lim = c(0,30))
```

# Grosse Dhuenn

```{r echo = FALSE}
lake <- "GrosseDhuenn"
lake_csv <- file.path(base_dir, "glm-examples", lake, "output/lake.csv") 
nc_file <- file.path(base_dir, "glm-examples", lake, "output/output.nc")
run_sim(lake, do_run, base_dir, glm_exec)
```

## Temperature profiles

```{r GrosseDhuenn, echo = FALSE}
plot_temp(nc_file, col_lim = c(0,30))
```

# Sparkling Lake

```{r echo = FALSE}
lake <- "Sparkling"
lake_csv <- file.path(base_dir, "glm-examples", lake, "output/lake.csv") 
nc_file <- file.path(base_dir, "glm-examples", lake, "output/output.nc")
run_sim(lake, do_run, base_dir, glm_exec)
```

## Temperature profiles

```{r Sparkling, echo = FALSE}
plot_temp(nc_file, col_lim = c(0,30))
```

# Lake Alexandrina

```{r echo = FALSE}
lake <- "LakeAlexandrina"
lake_csv <- file.path(base_dir, "glm-examples", lake, "output/lake.csv") 
nc_file <- file.path(base_dir, "glm-examples", lake, "output/output.nc")
run_sim(lake, do_run, base_dir, glm_exec)
```

## Temperature profiles

```{r LakeAlexandrina, echo = FALSE}
plot_temp(nc_file, col_lim = c(0,35))
```
